---
- name: Install Docker on remote nodes
  hosts: docker_nodes
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verify Docker Installation
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "Docker version installed: {{ docker_version.stdout }}"

